### ISSUE TITLE
SeAT 3.x

### ISSUE THREAD

**Issue by sergiorochalopes** [dysath/seat-srp#15]
hey!

Any plan on getting this to work with v3?

  Problem 1
    - denngarr/seat-srp 2.0.9 requires eveseat/services ^2.0 
...

Thank you!

**Comment by ZarosTenjin** [comment]
hey have a look at this issue: https://github.com/dysath/seat-srp/issues/5

**Comment by sergiorochalopes** [comment]
Doh!
Thanks
