### ISSUE TITLE
Feature request: Ping optional

### ISSUE THREAD

**Issue by kwazulueve** [dysath/seat-srp#16]
Minor feature request: It would be nice to have a setting that makes the 'Ping' field optional or not, or perhaps even visible or not.

In our corporation we have SRP for any PVP related loss, so in our case the Ping field is not needed

![image](https://user-images.githubusercontent.com/25641678/41263020-83047eae-6de4-11e8-9397-ea2455dc8ccc.png)

Thank you for this nice SeAT add-on!

**Comment by dysath** [comment]
Made field optional now in 3.0.0 stable
