### ISSUE TITLE
Feature Request: Allocate Payout Amount + Show person who Paid Out

### ISSUE THREAD

**Issue by jdrc** [dysath/seat-srp#18]
The use case here is:

1. SRP Request is submitted
2. Request is set as Approved
3. Request is set as Paid Out

On the Approved action allow the admin to enter the amount to be reimbursed (this will allow for a better tracking of the expense).

Once the Paid Out action is clicked have the Primary Character of the person who Paid Out displayed next to the request for tracking purposes.

A Statistics page which shows Paid Out amounts for stat tracking

**Comment by dysath** [comment]
Added the last person to click approve/paid out/etc. to the request.

Stat tracking will be something a bit larger to take on once I have some free cycles.

**Comment by dysath** [comment]
Stat tracking is now added.
