### ISSUE TITLE
Affiliation based permissions.

### ISSUE THREAD

**Issue by mossyblog** [dysath/seat-srp#23]
Rather than adding each individual user/group to get access to the SRP the affiliations should also enable the roles to have permissions we set.

For example all members in a corp should have access to "Srp.Request" permission by way of me adding "MyCorp" as he Affiliation.

However it doesn't react to this. Instead it requires individuals be added. When you have a corp thats 500+ its tedious work.

**Comment by herpaderpaldent** [comment]
Not really of any concern of this package. This is a RBAC issue that has been solved wit seat-groups plugin

**Comment by Crypta-Eve** [comment]
As stated by Herpaderp, in seat 3 this was solved through the use of their seat-groups plugin. In seat 4 this is solved through the use of squads
