### ISSUE TITLE
SRP Metrics - Wrong data

### ISSUE THREAD

**Issue by MagnusIIIBR** [dysath/seat-srp#27]
![image](https://user-images.githubusercontent.com/9530663/47954257-e1a2c800-df66-11e8-8941-5a4f6b3c6baa.png)
![image](https://user-images.githubusercontent.com/9530663/47954270-0dbe4900-df67-11e8-9128-50abe79a46e8.png)

In this current month i have paid 1 SRP and in the srp-metrics json not showing the paid ship and the outstanding requests

![image](https://user-images.githubusercontent.com/9530663/47954254-db145080-df66-11e8-8564-3db56a0a9a97.png)

**Comment by Crypta-Eve** [comment]
I believe this is fixed. Closing due to age.
