### ISSUE TITLE
Hope to get more information when reading killmail and store it in the database

### ISSUE THREAD

**Issue by KinomotoKi** [dysath/seat-srp#35]
The following are currently stored in the database:
            'srpCharacterName'
            'srpKillId'
            'srpKillToken'
            'srpCost'
            'srpShipType'
            'srpTypeId'

But killmail-url itself has more useful content:

For example

https://esi.evetech.net/latest/killmails/81830097/d14556cbecc852bd0ea337dad4475b5df1b4b1ab/

killmail_id | _killmail_time_ | _solar_system_id_ | _victim.alliance_id_ | _victim.corporation_id_ | victim.damage_taken | victim.position.x | victim.position.y | victim.position.z | victim.ship_type_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
81830097 | _2020-02-23T09:23:55Z_ | _30004346_ | _99008802_ | _98173218_ | 106051383 | -94641979754 | 8566774708 | 87907634423 | 35834

Hope you can complete this information in _italics_ and store it in the database
This information will be very useful for approval :)

thank you
o7

**Comment by Crypta-Eve** [comment]
Is this served currently for you at the moment with the link to zkillboard, or would perhaps a modal popup with the kill information be an option?

**Comment by Crypta-Eve** [comment]
With release 4.2.0 this information is pulled and stored in the database. Not shown as at this time but that will come later.
