### ISSUE TITLE
Request: Customise SRP Method

### ISSUE THREAD

**Issue by Jamesw13** [dysath/seat-srp#39]
Hi there,

This is a great tool and we use it for all of our SRP requests. However as an alliance, like many we only carry out SRP for the ship Hull.

It would be incredibly useful for many if there was an option to adjust settings to be able to have SRP value to be a % of the whole value, just Hull or excluding cargo ect.

This would be great for us as we would like to better monitor the metrics however these do not reflect what was paid.

Also the option for the value in Seat to reflect the Zkill value after the above settings so that I don't have to open zkill killmail to get the payout value would be additionally useful.

Kind regards,

Ascenity

**Comment by olanguedoc** [comment]
Yes! This would be amazing! :)

**Comment by Crypta-Eve** [comment]
This is implemented in release 4.2.0
