### ISSUE TITLE
Migration ERROR "Base Table already exists"

### ISSUE THREAD

**Issue by kaho88** [dysath/seat-srp#46]
Hey,

we try to Update to the new SRP Version.
After Updating we got some error and tryd to reinstall.

Now we arnt able to reinstall the SRP Addon and we get this Error:

```
´´php artisan migrate
Migrating: 2020_03_01_231218_migrate_srp_version_four

   Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'seat_srp_srp_three' already exists (SQL: CREATE TABLE seat_srp_srp_three LIKE seat_srp_srp)

  at /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'seat_srp_srp_three' already exists")
      /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129

  2   PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'seat_srp_srp_three' already exists")
      /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127

  Please use the argument -v to see more details.
´´
```

Anything we can do to improve? :)

**Comment by Crypta-Eve** [comment]
What this tells me is that the SRP plugin has already run migrations, but was interrupted. So you need to figure out where the migration got up to. Can you give me the output of `DESCRIBE seat_srp_srp;` from a database shell?

**Comment by kaho88** [comment]
Hey,

sorry for the late reply

Attached you find the output from the table
![srp db](https://user-images.githubusercontent.com/24758285/91561311-ab081f80-e93b-11ea-9118-c846a1b8318b.png)

**Comment by Crypta-Eve** [comment]
ok, so it looks like you have interrupted the migration partway through. You should always be very careful about killing a container during migrations as it leads to this situation. 

Do you have any previous data in seat3 that is important to you? Or is this a fresh install?

**Comment by kaho88** [comment]
The thing is, it was installed in the V4 Version and did also work.
We had problem with Warlof's connector Plugin... the Identities part wasnt pointable without an ERROR.

So we deinstalled all Plugins. After Fixing the connector we tryd to reinstall the SRP Plugin and it gave us instant this error.

We Updated from V3 to V4. 

The SRP table isnt that Important for us. So if you could give us a informations wat tables we need to delete to start a fresh install of the SRP Plugin would be fine also :-)

**Comment by Crypta-Eve** [comment]
If you send me an email at crypta@crypta.tech with the following I will
reply with the db commands you need.

`SELECT * FROM migrations;`

`DESCRIBE seat_srp_srp;`

`DESCRIBE seat_srp_srp_three;`

It won't be an immediate response but will get to it.

**Comment by QueerCodingGirl** [comment]
That "some error" mentioned in the first post was by any chance "stdclass property id does not exists"? I fixed it here: https://github.com/dysath/seat-srp/pull/53

...and you need to drop the backup table "seat_srp_srp_three" after a failed run of the migration.

**Comment by Crypta-Eve** [comment]
Thanks to @DarkGigaByte for the PR, that should solve this issue I do believe :)
