### ISSUE TITLE
Not good page when go to aproval 

### ISSUE THREAD

**Issue by marazmatik** [dysath/seat-srp#55]
Seat 4, Ubuntu 20, manual installation.

Installed: v4.0.4

Killmail https://esi.evetech.net/v1/killmails/80530360/b5ed5021fbbc80447eae07a680148bb88eb0a2c9/?datasource=tranquility

Have such page when go to aproval.

![image](https://user-images.githubusercontent.com/2928910/94749235-0b9bd980-038c-11eb-9b3e-be55f780a9b2.png)

**Comment by Crypta-Eve** [comment]
Yeah ny bad, this was because I added a header which expects all requests to be https. Will fix that asap
