### ISSUE TITLE
Custom payout amount

### ISSUE THREAD

**Issue by olanguedoc** [dysath/seat-srp#59]
I have a suggestion for the SRP module. When checking the "PAID OUT" tag, it would be nice to be able to write the amount that was paid out.  That amount would be taken into account for the SRP stats.  Its not everybody that pays out 100% of ship value. (I know i am cheap).

**Comment by Crypta-Eve** [comment]
Whilst not configurable on individual killmail basis, release 4.2.0 allows for very fine configuration of payout amounts.
