### ISSUE TITLE
cant access srp approval pager

### ISSUE THREAD

**Issue by HueRad** [dysath/seat-srp#74]
![image](https://user-images.githubusercontent.com/87426509/125619780-ea223f24-0897-4d3f-b420-6901ea3d2474.png)

this  happened after update 4.2.5

**Comment by Crypta-Eve** [comment]
You will need to troubleshoot this further in order to understand what is going on. The full error will be available in the laravel logs (if using docker then check the seat-web) container.

**Comment by Crypta-Eve** [comment]
Closing due to age and no response
