### ISSUE TITLE
Receiving DataTables warning when entering SRP module settings on a new installation.

### ISSUE THREAD

**Issue by SuperSixOne** [dysath/seat-srp#82]
Good Evening, 

Retrieving the following message when entering the SRP > Settings menu.

'DataTables warning: table id=group_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7'

The warning is generating off of the Group Rules section of the page. (I can interact and save all other controls on the page), but cannot set any Group Rules.

Stack from Chrome Console:
  | (anonymous) | @ | VM2259:1
-- | -- | -- | --
  | send | @ | jquery.min.js:4
  | ajax | @ | jquery.min.js:4
  | Oa | @ | jquery.dataTables.min.js:50
  | Gb | @ | jquery.dataTables.min.js:50
  | ja | @ | jquery.dataTables.min.js:42
  | ka | @ | jquery.dataTables.min.js:44
  | pc | @ | jquery.dataTables.min.js:127
  | (anonymous) | @ | jquery.dataTables.min.js:128
  | iterator | @ | jquery.dataTables.min.js:119
  | (anonymous) | @ | jquery.dataTables.min.js:128
  | (anonymous) | @ | jquery.dataTables.min.js:122
  | success | @ | settings:2515
  | i | @ | jquery.min.js:2
  | fireWith | @ | jquery.min.js:2
  | z | @ | jquery.min.js:4
  | (anonymous) | @ | jquery.min.js:4
  | load (async) |   |  
  | send | @ | jquery.min.js:4
  | ajax | @ | jquery.min.js:4
  | (anonymous) | @ | settings:2499
  | dispatch | @ | jquery.min.js:3
  | r.handle | @ | jquery.min.js:3

This is a docker installation of Seat for reference.

**Comment by Crypta-Eve** [comment]
Welp, nearly a year later. This is likely the SDE being not yet populated.
