### ISSUE TITLE
Errors getting info from killmail

### ISSUE THREAD

**Issue by iwasinnamuknow** [dysath/seat-srp#87]
Suddenly overnight we are unable to post killmails after it has been working well for a month. It responds with errors that it is unable to get info from the killmail:

![error](https://github.com/dysath/seat-srp/assets/26540/6e2e50df-4789-47b9-baf3-27874012ebb2)

Manually browsing the killmail link looks normal, with all the expected JSON data. I haven't checked if the format is exactly the same but it looks right.

Wondering if this could be related to #86 but I wouldn't expect the lack of price info to cause this.

**Comment by iwasinnamuknow** [comment]
After an update/restart of the containers we're now getting "Invalid killmail address" for any killmail links we try. These links are copied directly from in-game combat log.

I notice that the in-game links point to esi.evetech.net whereas the placeholder text in the killmail entry is esi.tech.ccp.is. Unfortunately just changing the hostname doesn't provide a valid killmail response.

**Comment by FeiBam** [comment]
Beacuse https://evepraisal.com/ shut down. this serviceThis plugin depends on https://evepraisal.com/

**Comment by FeiBam** [comment]
I suggest adding a configuration option，User-friendly designation of valuation sites

**Comment by Crypta-Eve** [comment]
This has been addressed with #90
