### ISSUE TITLE
External URL changed by CCP / Submitting Killmails no longer working.

### ISSUE THREAD

**Issue by metronade** [dysath/seat-srp#88]
External URL expect "https://esi.tech.ccp.is/v1/killmails/***" but ccp changed it to "https://esi.evetech.net/v1/killmails/***"

So we get External URL is invalid as answer.

**Comment by Crypta-Eve** [comment]
The url has not changed. Yes, the placeholder is wrong however this does not affect the ability to submit the killmail. What is actually happening is that the website used for pricing, evepraisal, was banned by CCP and as a result has shut down. This has been corrected though #90
