### ISSUE TITLE
Docker-Compose Install Not Working

### ISSUE THREAD

**Issue by paintballlaws** [dysath/seat-srp#9]
When trying to install this plugin with docker-compose it still try's to pull the version 2.0 instead of the new 3.0 version. Is there any way to fix it to when I add your plugin into the .env file it will automatically pull v3.0?

**Comment by vanhemn** [comment]
use composer require denngarr/seat-srp:~3.0

**Comment by paintballlaws** [comment]
that throws an invalid string when adding that to the plugins list
`SeAT Plugins
 This is a list of the all of the third party plugins that you
 would like to install as part of SeAT. Package names should be
 comma separated if multiple packages should be installed.
SEAT_PLUGINS=denngarr/seat-fitting,kassie/calendar,composer require denngarr/seat-srp:~3.0`

**Comment by paintballlaws** [comment]
I assume that I am trying to go about this the wrong way but

**Comment by vanhemn** [comment]
root@vps498246:/var/www/seat# php artisan down
Application is now in maintenance mode.
root@vps498246:/var/www/seat# composer require denngarr/seat-srp:~3.0
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been updated

that work for me

**Comment by paintballlaws** [comment]
that directory does not exist for me as I do not have a web server installed

**Comment by paintballlaws** [comment]
warlof answered my question in slack, He said it is caused because there is no release tag.

**Comment by paintballlaws** [comment]
@Dracks977 after it comes back and tells you the composer has been updated what do you do after that? I tried what is in the readme but that didnt work?

**Comment by paintballlaws** [comment]
scratch that I corrected my own deficiency
